sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t kpkp00014/docker-react-app -f Dockerfile.Dev .

script:
  - docker run -e CI=true kpkp00014/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"
